spring.datasource.url=jdbc:postgresql://dpg-d75plp9r0fns73f8vvkg-a.singapore-postgres.render.com:5432/booking_db_fq2h
spring.datasource.username=booking_db_fq2h_user
spring.datasource.password=RJ1fp3SncNHfI0AskR9cpLex59roW60t

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}

server.id=5